steps:

  - id: "Enable Google IAM APIs"
    name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "services",
        "enable",
        "iam.googleapis.com",
        "--project",
        "$PROJECT_ID"
      ]

  - id: "Enable Google Cloud Resource Manager APIs"
    name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "services",
        "enable",
        "cloudresourcemanager.googleapis.com",
        "--project",
        "$PROJECT_ID"
      ]

  - id: "Enable Google CloudFunctions APIs"
    name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "services",
        "enable",
        "cloudfunctions.googleapis.com",
        "--project",
        "$PROJECT_ID"
      ]

  - id: "Enable App Engine Admin API"
    name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "services",
        "enable",
        "appengine.googleapis.com",
        "--project",
        "$PROJECT_ID"
      ]

  - id: "Enable Firestore API"
    name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "services",
        "enable",
        "firestore.googleapis.com",
        "--project",
        "$PROJECT_ID"
      ]

  - id: "Create App Engine App"
    name: gcr.io/cloud-builders/gcloud
    entrypoint: /bin/bash
    args:
     - -c
     - |
       gcloud app create --region=europe-west || echo App engine already exists

  - id: "Create Balance PubSub Topic"
    name: gcr.io/cloud-builders/gcloud
    entrypoint: /bin/bash
    args:
      - -c
      - |
        topic_ref=$(gcloud pubsub topics list | grep ${_BALANCE_TOPIC_NAME})
        if [[ $topic_ref = '' ]]; then
          gcloud pubsub topics create ${_BALANCE_TOPIC_NAME}
        else
          echo Balance topic already exists
        fi

  - id: "Create Transaction PubSub Topic"
    name: gcr.io/cloud-builders/gcloud
    entrypoint: /bin/bash
    args:
      - -c
      - |
        topic_ref=$(gcloud pubsub topics list | grep ${_TRANSACTION_TOPIC_NAME})
        if [[ $topic_ref = '' ]]; then
          gcloud pubsub topics create ${_TRANSACTION_TOPIC_NAME}
        else
          echo Balance topic already exists
        fi

substitutions:
    _BALANCE_TOPIC_NAME: balance
    _TRANSACTION_TOPIC_NAME: transactions
